In [15]:
import numpy as np

my_list = [3, 2, 1, 4]
array_list = np.array(my_list)
shape = array_list.reshape(2, 2)
print(shape)


[[3 2]
 [1 4]]


In [16]:
arr2 = np.array([[-2,1] ,[1, 3]])
arr_rand = np.random.rand(2, 2)
arr2 = arr2 * 2
ans = arr2 - arr_rand + shape
print(ans)

[[-1.55616474  3.24803997]
 [ 2.71912551  9.93508258]]


In [17]:
x = ans[0]
x = np.concatenate((x, x))
print(x)

[-1.55616474  3.24803997 -1.55616474  3.24803997]


In [18]:
xmin = x.min()
xmax = x.max()
ans2 = xmin * xmax
print(f"min * max = {xmin} * {xmax}")
print(ans2)

min * max = -1.5561647390987243 * 3.248039967108083
-5.054485267996979


In [19]:
x 

array([-1.55616474,  3.24803997, -1.55616474,  3.24803997])