In [1]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [39]:
my_list = [30, 20, 10, 40]
print(f"original = {my_list}")

x = torch.tensor(my_list).reshape(2, 2)
print(x)

y = torch.tensor([[-2, 1], [1, 3]])
z = torch.rand(2, 2)

ans = x + (2*y) + z
print(ans)

slice_1 = ans[:, 0].reshape(2, 1)
slice_2 = ans[:, 1].reshape(2, 1)

ans2 = torch.concat((slice_1, slice_2), dim=0)
print(ans2)

ans3 = ans2.min()*ans2.max()
ans3 = torch.unsqueeze(ans3, dim=0)
print(ans3)

original = [30, 20, 10, 40]
tensor([[30, 20],
        [10, 40]])
tensor([[26.9022, 22.9173],
        [12.4703, 46.9455]])
tensor([[26.9022],
        [12.4703],
        [22.9173],
        [46.9455]])
tensor([585.4255])
