In [9]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [29]:
x = [0, 1, 2, 3]
print(f"original = {x}")

x = torch.tensor(x, device=device).reshape(2, 2)
print(x)

y = torch.tensor([[0, 1], [0, 4]], device=device)
z = torch.rand(2, 2, device=device)

x = x + (-5 * y) - z
print(x)

slice = x[0, :]
print(f"slice = {slice}")

ans = torch.cat((slice, slice), dim=0)
print(f"ans = {ans}")


original = [0, 1, 2, 3]
tensor([[0, 1],
        [2, 3]], device='cuda:0')
tensor([[ -0.8805,  -4.0749],
        [  1.4081, -17.9558]], device='cuda:0')
slice = tensor([-0.8805, -4.0749], device='cuda:0')
ans = tensor([-0.8805, -4.0749, -0.8805, -4.0749], device='cuda:0')


In [42]:
x = torch.arange(10).reshape(2, 5)
print(x)
print(x.permute(1, 0))
print(x.t())

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


In [ ]:
x = torch.empty(size = (2, 5))
x = torch.zeros((2, 5))
x = torch.ones((2, 5))
x = torch.rand((2, 5))
x = torch.randn((2, 5))
x = torch.randint(0, 10, (2, 5))
x = torch.eye(2, 5)
x = torch.linspace(1, 10, steps=10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [66]:
import numpy as np
np_array = np.array([0, 1, 2, 3])
print(np_array)
x = torch.from_numpy(np_array)
x

[0 1 2 3]


tensor([0, 1, 2, 3])

In [70]:
x0 = torch.rand(5)
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2D x 2D only
x3 = torch.matmul(x1, x2) # General Purpose
x3 = torch.dot(x0, x0)
x3

tensor(1.0324)